### PR TITLE
IT2 - season stats: fewest_tackles

### LINKED ISSUE #11: Season Stats - fewest_tackles
These methods each take a season id as an argument and return the values described below.

Description
Name of the Team with the fewest tackles in the season

Return Value
String

### PR DESCRIPTION
**Pull request by leahriffell**
**Helper method added:** 
- `tackles_per_team_for(season_id)`

**Season stat added:** 
- `fewest_tackles(season_id)`

closes #11

### CODE REVIEW

**Review by hopesgit — APPROVED** [review]

**Review by AngelaGuardia — APPROVED** [review]
This is really well done Leah!

**Review by sarynm12 — APPROVED** [review]
Great work, Leah! I'm gonna go ahead and merge since we've all 3 reviewed it!

**Comment by sarynm12** [comment]
Actually, it says there's a merge conflict! I'll take a look, but I don't wanna screw anything up before merging! Let me see what it says

**Comment by leahriffell** [comment]
Thanks @sarynm12! I just fixed the merge conflicts.

**Comment by sarynm12** [comment]
Thank you, Leah! I'll merge!

**Pull request merged**
